SELECT 
    TRIM(F.RDB$FIELD_NAME) AS DOMAIN_NAME,
    F.RDB$FIELD_TYPE AS FIELD_TYPE,
    F.RDB$FIELD_LENGTH AS FIELD_LENGTH,
    F.RDB$CHARACTER_LENGTH AS DATA_CHAR_LENGTH,
    F.RDB$FIELD_SCALE AS FIELD_SCALE,
    F.RDB$NULL_FLAG AS NULL_FLAG,
    TRIM(F.RDB$DEFAULT_SOURCE) AS DEFAULT_SOURCE
FROM RDB$FIELDS F
WHERE F.RDB$SYSTEM_FLAG = 0 
  AND F.RDB$FIELD_NAME NOT LIKE 'RDB$%'
ORDER BY F.RDB$FIELD_NAME