SELECT 
    TRIM(pp.RDB$PARAMETER_NAME) AS PARAM_NAME,
    pp.RDB$PARAMETER_TYPE AS PARAM_TYPE,
    f.RDB$FIELD_TYPE AS FIELD_TYPE,
    f.RDB$FIELD_LENGTH AS FIELD_LENGTH,
    f.RDB$CHARACTER_LENGTH AS DATA_CHAR_LENGTH,
    f.RDB$FIELD_SCALE AS FIELD_SCALE,
    TRIM(f.RDB$FIELD_NAME) AS DOMAIN_NAME
FROM RDB$PROCEDURE_PARAMETERS pp
JOIN RDB$FIELDS f ON pp.RDB$FIELD_SOURCE = f.RDB$FIELD_NAME
WHERE pp.RDB$PROCEDURE_NAME = @ProcName
ORDER BY pp.RDB$PARAMETER_TYPE, pp.RDB$PARAMETER_NUMBER