SELECT 
    TRIM(rf.RDB$FIELD_NAME) AS COLUMN_NAME,
    f.RDB$FIELD_TYPE AS FIELD_TYPE,
    f.RDB$FIELD_LENGTH AS FIELD_LENGTH,
    f.RDB$CHARACTER_LENGTH AS DATA_CHAR_LENGTH,
    f.RDB$FIELD_PRECISION AS FIELD_PRECISION,
    f.RDB$FIELD_SCALE AS FIELD_SCALE,
    rf.RDB$NULL_FLAG AS NULL_FLAG,
    TRIM(f.RDB$FIELD_NAME) AS DOMAIN_NAME
FROM RDB$RELATION_FIELDS rf
JOIN RDB$FIELDS f ON rf.RDB$FIELD_SOURCE = f.RDB$FIELD_NAME
WHERE rf.RDB$RELATION_NAME = @TableName
ORDER BY rf.RDB$FIELD_POSITION